llm:
  models:
    - model_name: "qwen2.5-72b-instruct"
      description: "Primary model for general tasks"
      api_key: ""
      base_url: "https://qwen.aliyuncs.com/v1"
      max_tokens: 2048
      temperature: 0.7
      top_p: 0.9

    - model_name: "deepseek-chat"
      description: "DeepSeek-V3"
      api_key: ""
      base_url: "https://api.deepseek.com"
      max_tokens: 5000
      temperature: 1.5
      top_p: 0.8









